import { TestsDone, testGradient } from '../data/dataDashboard';


export default function Dashboard() {
  const getButtonGradient = (modelName) => {
    const post = testGradient.find(post => post.title === modelName);
    return post ? post.buttonGradient : 'from-emerald-500 to-blue-500';
  };

  return (
    <div className="bg-slate-100 py-10">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        <div className="mx-auto max-w-2xl text-center">
          <h3 className="font-semibold tracking-tight text-emerald-400">
            DASHBOARD
          </h3>

          <h2 className="text-3xl font-bold tracking-tight text-gray-800 lg:text-6xl">
            Model Reports 📊
          </h2>

          <p className="mt-2 text-lg leading-8 text-gray-600">
            Here you will find all the reports generated by our models.
          </p>
        </div>
        <div className="mx-auto mt-16 grid max-w-2xl auto-rows-fr grid-cols-1 gap-8 sm:mt-20 lg:mx-0 lg:max-w-none lg:grid-cols-3">
          {TestsDone.map((test, index) => (
            <article
              key={index}
              className="relative isolate flex flex-col justify-end overflow-hidden rounded-2xl bg-white px-8 pb-8 pt-5 sm:pt-8 lg:pt-8 shadow-xl"
            >
              <div className="absolute inset-0 -z-10" />
              <h3 className="mt-1 text-lg font-semibold leading-6 text-black">
                <a href={test.href}>
                  <span className="absolute inset-0" />
                  {test.model}
                </a>
              </h3>
              <p className="mt-1 text-black">{test.report}</p>
              <button
                type="button"
                className={`mt-4 rounded-md bg-gradient-to-r ${getButtonGradient(test.model)} px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm`}
              >
                View Report
              </button>
            </article>
          ))}
        </div>
      </div>
    </div>
  );
}
